# Exercice Numpy

## Exercice 1 : Les constructeurs

In [1]:
import numpy as np
from numpy import random


In [2]:
#Constructeur du tableau contenant les éléments 1, 5, 7 et 8

tableau_1 = np.array([1, 5, 7, 8])
tableau_1

array([1, 5, 7, 8])

In [3]:
#Constructeur du tableau contenant les éléments 1, 2, 3, 4, 5, 6, 7, 8 et 9

tableau_2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
tableau_2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#Constructeur du tableau contenant des 0

tableau_3 = np.zeros([4])
tableau_3

array([0., 0., 0., 0.])

In [5]:
#Constructeur du tableau contenant 2 lignes et 4 colonnes rempli de 0

tableau_4 = np.zeros([2, 4])
print(tableau_4)
tableau_4.dtype

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


dtype('float64')

In [6]:
#Constructeur du tableau de 2 lignes 5 colonnes rempli de 1

tableau_5 = np.ones([2, 5])

In [7]:
tableau_5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
#Constructeur du tableau de 10 éléments rempli 8.5

tableau_6 = np.ones([10])*8.5 #ou np.ones(10)*8.5 ou np.full(10,8.5)
tableau_6

array([8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5])

In [9]:
#Constructeur du tableau de série d'entiers successifs allant de 1 à 9 inclus

tableau_7 = np.arange(1, 10)
tableau_7

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#Constructeur du tableau de 3 lignes et 3 colonnes rempli de série d'entiers successifs allant de 1 à 9 inclus

tableau_8 = tableau_7.reshape(3, 3)

tableau_8


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
#Création d'une matrice identé de 4 lignes 4 colonnes

matrice_identite = np.eye(4) #ou np.identity(4)
matrice_identite

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
#Création d'un tableau rempli de valeurs aléatoires normales centrées en zéro

tableau_random1 = random.rand(5)
tableau_random1

array([0.94933287, 0.53700234, 0.05578164, 0.59401551, 0.56790447])

In [13]:
#Création d'un tableau rempli de 20 valeurs aléatoires entières comprises entre 1 et 10

tableau_random2 = np.random.randint(1,11, size = (20))
print(tableau_random2)
print(len(tableau_random2))

[ 7  8  4 10  2 10  6  1  9  9  3  9  7  6  9  1  4  7 10  7]
20


In [14]:
#Transformation du tableau précédent en matrice de 4 lignes et 5 colonnes
lst1 = tableau_random2

lst1.reshape(4,5)


array([[ 7,  8,  4, 10,  2],
       [10,  6,  1,  9,  9],
       [ 3,  9,  7,  6,  9],
       [ 1,  4,  7, 10,  7]])

In [15]:
#Créer un tableau de 5 éléments compris entre 0 et 1 avec une amplitude égale 5
n = random.rand(1)
#n += 1
amplitude_egale = np.full((3, 3), n)

print(amplitude_egale)

[[0.36718397 0.36718397 0.36718397]
 [0.36718397 0.36718397 0.36718397]
 [0.36718397 0.36718397 0.36718397]]


## Exercice 2 : Les attributs d'un tableau numpy

## Soit le tableau a = np.array([[1,2,3],[4,5,6],[7,8,9]])





In [16]:
#Affichons le nombre de lignes et de colonnes de a

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a_ligne_colonne = a.shape
a_ligne = a_ligne_colonne[0]
a_colonne = a_ligne_colonne[1]
print(f"Nombre ligne: {a_ligne}")
print(f"Nombre colonne: {a_colonne}")

Nombre ligne: 3
Nombre colonne: 3


In [17]:
#Affichons la dimension de mon tableau
a_dimension = a.ndim
print(f"Dimension: {a_dimension}")

Dimension: 2


In [18]:
#Affichons le nombre d'élément de mon tableau
a_nombre_element = a.size
print(f"Nombre élément: {a_nombre_element}")


Nombre élément: 9


In [19]:
#Affichons le type des éléments du tableau
a_dtype = a.dtype
a_dtype

dtype('int64')

## Exercice 3 : Indexing, slicing, subsetting, masking

In [20]:
#Affichons la valeur 5 qui est dans le tableau
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
a_slice_5 = a[1,1]
a_slice_5

5

In [21]:
#Remplaçons le 5 qui est dans le tableau par 0
a[1, 1] = 0
a

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [22]:
#Affichons les chiffres 3, 6 et 9 du tableau
a_slicing_3_6_9 = a[:,-1]
a_slicing_3_6_9

array([3, 6, 9])

In [23]:
#créer un tableau de 4 lignes et 3 colonnes rempli de 12 nombres entiers aléatoires compris entre 0 et 9
new_tableau_random = np.random.randint(10, size=(4,3))
new_tableau_random

array([[6, 6, 4],
       [5, 3, 1],
       [9, 8, 3],
       [0, 8, 7]])

In [24]:
#Vérifier qu’il y a des nombres inférieur à 5
for index in new_tableau_random:
    for i in index:
        if i < 5:
            print(f"{i} est inférieur à 5")

            
check = np.any(new_tableau_random < 5)
check

#np.new_tableau_random
        

4 est inférieur à 5
3 est inférieur à 5
1 est inférieur à 5
3 est inférieur à 5
0 est inférieur à 5


True

In [25]:
#Remplacer les nombres inférieurs à 5 par 0
np.where(check ,0, new_tableau_random )
            

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Exercice 4

In [26]:
#Créer un tableau de 4 lignes et 3 colonnes rempli de 12 nombres entiers aléatoires compris entre 0 et 9
mon_tableau = np.random.randint(10, size=(4,3))
mon_tableau

array([[7, 1, 1],
       [3, 7, 5],
       [0, 4, 5],
       [0, 8, 6]])

In [27]:
#Quel est le type des éléments du tableau ?
type_tableau = mon_tableau.dtype
type_tableau

dtype('int64')

In [28]:
#Changer de type des éléments du tableau en float32
new_type = mon_tableau.astype('float32')
new_type.dtype

dtype('float32')

In [29]:
#Ajouter le chiffre 3 à la fin du tableau à une dimension
new_tableau = np.append(new_type, 3)
new_tableau

array([7., 1., 1., 3., 7., 5., 0., 4., 5., 0., 8., 6., 3.])

In [30]:
#Transformer le tableau en matrice dénommée “a” de 3 lignes et 4 colonnes
new_tableau = np.delete(new_tableau, -1)
a = new_tableau.reshape(3,4)
a

array([[7., 1., 1., 3.],
       [7., 5., 0., 4.],
       [5., 0., 8., 6.]])

In [31]:
#Créons une matrice dénommée “b” de 3 lignes et 4 colonnes remplie de série d'entiers successifs allant de 1 à 12 inclus
b = np.arange(1,13)
b = b.reshape(3, 4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
#Créons une matrice dénommée “c” qui est la concaténation des deux tableaux “a” et “b” dans le sens horizontale
c=np.hstack((a,b))
c

array([[ 7.,  1.,  1.,  3.,  1.,  2.,  3.,  4.],
       [ 7.,  5.,  0.,  4.,  5.,  6.,  7.,  8.],
       [ 5.,  0.,  8.,  6.,  9., 10., 11., 12.]])

In [33]:
d=np.vstack((a,b))
d

array([[ 7.,  1.,  1.,  3.],
       [ 7.,  5.,  0.,  4.],
       [ 5.,  0.,  8.,  6.],
       [ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [34]:
#Aplatissons le tableau d
d = np.ravel(d)
d

array([ 7.,  1.,  1.,  3.,  7.,  5.,  0.,  4.,  5.,  0.,  8.,  6.,  1.,
        2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [35]:
#Supprimons le dernier élément du tableau
d= np.delete(d,-1)
d
  

array([ 7.,  1.,  1.,  3.,  7.,  5.,  0.,  4.,  5.,  0.,  8.,  6.,  1.,
        2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

## Exercice : Statistique avec numpy

In [36]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
#Affichons la somme des éléments du tableau
a_somme = a.sum()
print(a)
print(a_somme)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45


In [37]:
#Affichons la somme des éléments du tableau par colonne
a.sum(axis=0)

array([12, 15, 18])

In [38]:
#Affichons la somme des éléments du tableau par ligne
a_somme_list = a.sum(axis=1)
a_somme_list

array([ 6, 15, 24])

In [39]:
#Affichons le produit des éléments du tableau par colonne
prodruit_colonne = np.prod(a, axis=0)
prodruit_colonne

array([ 28,  80, 162])

In [40]:
#Affichons le minimum du tableau
a_min = a.min()
a_min

1

In [41]:
#Affichons la mayonne des éléments du tableau
a_max = a.max()
a_max
     

9

In [42]:
#Affichons la variance des éléments du tableau
a_var = a.var()
a_var
     

6.666666666666667

In [43]:
#Afficher l’écart type des éléments du tableau
a_sts = a.std()
a_sts

2.581988897471611